# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alleles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'alleles',
                'verbose_name_plural': 'Alleles',
            },
        ),
        migrations.CreateModel(
            name='Arenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'arenas',
                'verbose_name_plural': 'Arenas',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentalStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'developmental_stages',
                'verbose_name_plural': 'Developmental Stages',
            },
        ),
        migrations.CreateModel(
            name='ExitFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('track_checkpoint', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'exit_flags',
                'verbose_name_plural': 'Exit Flags',
            },
        ),
        migrations.CreateModel(
            name='Experimenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'experimenters',
                'verbose_name_plural': 'Experimenters',
            },
        ),
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'experiments',
                'verbose_name_plural': 'Experiments',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'foods',
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'genes',
                'verbose_name_plural': 'Genes',
            },
        ),
        migrations.CreateModel(
            name='Habituations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'habituations',
                'verbose_name_plural': 'Habituations',
            },
        ),
        migrations.CreateModel(
            name='SegwormComparisons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_mutual_skeletons', models.IntegerField(blank=True, null=True)),
                ('error_05th', models.FloatField(blank=True, null=True)),
                ('error_50th', models.FloatField(blank=True, null=True)),
                ('error_95th', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'segworm_comparisons',
                'verbose_name_plural': 'Segworm Comparisons',
            },
        ),
        migrations.CreateModel(
            name='SegwormFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('n_valid_skeletons', models.IntegerField(blank=True, null=True)),
                ('n_timestamps', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'segworm_features',
                'verbose_name_plural': 'Segworm Features',
            },
        ),
        migrations.CreateModel(
            name='Sexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'sexes',
                'verbose_name_plural': 'Sexes',
            },
        ),
        migrations.CreateModel(
            name='Strains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('genotype', models.CharField(blank=True, max_length=200, null=True)),
                ('allele', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Alleles')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Genes')),
            ],
            options={
                'db_table': 'strains',
                'verbose_name_plural': 'Strains',
            },
        ),
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'trackers',
                'verbose_name_plural': 'Trackers',
            },
        ),
        migrations.CreateModel(
            name='VentralSides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'ventral_sides',
                'verbose_name_plural': 'Ventral Sides',
            },
        ),
        migrations.CreateModel(
            name='OriginalVideos',
            fields=[
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webworm.Experiments')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('directory', models.CharField(max_length=500)),
                ('sizemb', models.FloatField(blank=True, db_column='sizeMB', null=True)),
            ],
            options={
                'db_table': 'original_videos',
                'verbose_name_plural': 'Original Videos',
            },
        ),
        migrations.CreateModel(
            name='ProgressMasks',
            fields=[
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webworm.Experiments')),
                ('mask_file', models.CharField(blank=True, max_length=500, null=True)),
                ('n_valid_frames', models.IntegerField(blank=True, null=True)),
                ('n_missing_frames', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('exit_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.ExitFlags')),
            ],
            options={
                'db_table': 'progress_masks',
                'verbose_name_plural': 'Progress Masks',
            },
        ),
        migrations.CreateModel(
            name='ProgressTracks',
            fields=[
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webworm.Experiments')),
                ('skeletons_file', models.CharField(blank=True, max_length=500, null=True)),
                ('features_file', models.CharField(blank=True, max_length=500, null=True)),
                ('n_segmented_skeletons', models.IntegerField(blank=True, null=True)),
                ('n_filtered_skeletons', models.IntegerField(blank=True, null=True)),
                ('n_valid_skeletons', models.IntegerField(blank=True, null=True)),
                ('n_timestamps', models.IntegerField(blank=True, null=True)),
                ('first_frame', models.IntegerField(blank=True, null=True)),
                ('last_frame', models.IntegerField(blank=True, null=True)),
                ('exit_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.ExitFlags')),
            ],
            options={
                'db_table': 'progress_tracks',
                'verbose_name_plural': 'Progress Tracks',
            },
        ),
        migrations.AddField(
            model_name='segwormfeatures',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Experiments'),
        ),
        migrations.AddField(
            model_name='segwormcomparisons',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Experiments'),
        ),
        migrations.AddField(
            model_name='segwormcomparisons',
            name='segworm_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.SegwormFeatures'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Arenas'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='developmental_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.DevelopmentalStages'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='experimenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Experimenters'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Foods'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='habituation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Habituations'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Sexes'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Strains'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.Trackers'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='ventral_side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webworm.VentralSides'),
        ),
    ]
