# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webworm', '0002_db_250117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsSummary',
            fields=[
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webworm.Experiments')),
                ('n_valid_frames', models.IntegerField(blank=True, null=True)),
                ('n_missing_frames', models.IntegerField(blank=True, null=True)),
                ('n_segmented_skeletons', models.IntegerField(blank=True, null=True)),
                ('n_filtered_skeletons', models.IntegerField(blank=True, null=True)),
                ('n_valid_skeletons', models.IntegerField(blank=True, null=True)),
                ('n_timestamps', models.IntegerField(blank=True, null=True)),
                ('first_skel_frame', models.IntegerField(blank=True, null=True)),
                ('last_skel_frame', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('mask_file_sizemb', models.FloatField(blank=True, db_column='mask_file_sizeMB', null=True)),
            ],
            options={
                'db_table': 'results_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SegwormInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segworm_file', models.CharField(blank=True, max_length=700, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('n_segworm_skeletons', models.IntegerField(blank=True, null=True)),
                ('n_timestamps', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'segworm_info',
                'managed': False,
            },
        ),
    ]
