# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-02 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webworm', '0005_db_20170829'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierpsyFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tierpsy_features',
                'managed': False,
            },
        ),
    ]
