# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alleles',
            options={'verbose_name_plural': 'Alleles'},
        ),
        migrations.AlterModelOptions(
            name='arenas',
            options={'verbose_name_plural': 'Arenas'},
        ),
        migrations.AlterModelOptions(
            name='developmentalstages',
            options={'verbose_name_plural': 'Developmental Stages'},
        ),
        migrations.AlterModelOptions(
            name='exitflags',
            options={'verbose_name_plural': 'Exit Flags'},
        ),
        migrations.AlterModelOptions(
            name='experimenters',
            options={'verbose_name_plural': 'Experimenters'},
        ),
        migrations.AlterModelOptions(
            name='experiments',
            options={'verbose_name_plural': 'Experiments'},
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterModelOptions(
            name='genes',
            options={'verbose_name_plural': 'Genes'},
        ),
        migrations.AlterModelOptions(
            name='habituations',
            options={'verbose_name_plural': 'Habituations'},
        ),
        migrations.AlterModelOptions(
            name='originalvideos',
            options={'verbose_name_plural': 'Original Videos'},
        ),
        migrations.AlterModelOptions(
            name='progressmasks',
            options={'verbose_name_plural': 'Progress Masks'},
        ),
        migrations.AlterModelOptions(
            name='progresstracks',
            options={'verbose_name_plural': 'Progress Tracks'},
        ),
        migrations.AlterModelOptions(
            name='segwormcomparisons',
            options={'verbose_name_plural': 'Segworm Comparisons'},
        ),
        migrations.AlterModelOptions(
            name='segwormfeatures',
            options={'verbose_name_plural': 'Segworm Features'},
        ),
        migrations.AlterModelOptions(
            name='sexes',
            options={'verbose_name_plural': 'Sexes'},
        ),
        migrations.AlterModelOptions(
            name='strains',
            options={'verbose_name_plural': 'Strains'},
        ),
        migrations.AlterModelOptions(
            name='trackers',
            options={'verbose_name_plural': 'Trackers'},
        ),
        migrations.AlterModelOptions(
            name='ventralsides',
            options={'verbose_name_plural': 'Ventral Sides'},
        ),
    ]
